// controllers/PredictionController.js

'use strict'

const PlantService   = require('../services/PlantService')
const MLService      = require('../services/MLService')
const HistoryService = require('../services/HistoryService')
const asyncHandler   = require('../utils/asyncHandler')
const AppError       = require('../utils/AppError')
const { buildPredictionResponse, formatHistory } = require('../utils/dataTransform')

/**
 * POST /api/predict
 *
 * Body (one of):
 *   { plant1Id, plant2Id }  — MongoDB ObjectIds (used by React frontend)
 *   { plantA,   plantB   }  — scientific name strings
 */
const predictHybrid = asyncHandler(async (req, res) => {
  const body = req.body

  // ── 1. Resolve plant identifiers ────────────────────────────────────────────
  const idA   = body.plant1Id || body.plantAId
  const idB   = body.plant2Id || body.plantBId
  const nameA = body.plantA   || body.plant1Name || body.plantAName
  const nameB = body.plantB   || body.plant2Name || body.plantBName

  if (!idA && !nameA) {
    throw new AppError(
      'Provide plant1Id + plant2Id (ObjectIds) or plantA + plantB (names)',
      400, 'MISSING_PLANTS'
    )
  }

  // ── 2. Fetch both plant documents from MongoDB ──────────────────────────────
  let plantA, plantB

  if (idA && idB) {
    ;({ plantA, plantB } = await PlantService.getPairById(idA, idB))
  } else if (idA || idB) {
    plantA = idA ? await PlantService.getById(idA)   : await PlantService.getByName(nameA)
    plantB = idB ? await PlantService.getById(idB)   : await PlantService.getByName(nameB)
    if (plantA._id.toString() === plantB._id.toString()) {
      throw new AppError('Both plants must be different', 400, 'SAME_PLANT')
    }
  } else {
    if (!nameB) throw new AppError('Provide both plantA and plantB names', 400, 'MISSING_PLANTS')
    ;({ plantA, plantB } = await PlantService.getPairByName(nameA, nameB))
  }

  // ── 3. Call ML API ──────────────────────────────────────────────────────────
  const { traits, hybridName, source, confidence } = await MLService.predict(plantA, plantB)

  // ── 4. Build response (generates trait_descriptions) ────────────────────────
  const responseData = buildPredictionResponse({
    plantA:    plantA.plant_name,
    plantB:    plantB.plant_name,
    traits,
    hybridName,
    source,
    plantADoc: plantA,
    plantBDoc: plantB,
  })

  // ── 5. Save to history ──────────────────────────────────────────────────────
  const historyRecord = await HistoryService.save({
    plantA,
    plantB,
    traits,
    hybridName,
    source,
    traitDescriptions: responseData.trait_descriptions,
    // hybrid_image_url is left empty — image is generated live on the frontend
    // via Pollinations AI using the predicted traits as a text prompt.
    hybridImageUrl: '',
  })

  // ── 6. Send response ────────────────────────────────────────────────────────
  // plantA_image and plantB_image (from DB) are sent for display in the lineage panel.
  // The AI hybrid image is generated on the frontend — no server-side image processing needed.
  res.status(200).json({
    success:    true,
    data: {
      ...responseData,
      confidence,
      plantA_image: plantA.image_url || '',  // parent A image from MongoDB
      plantB_image: plantB.image_url || '',  // parent B image from MongoDB
      // hybrid_image is intentionally omitted — generated by Pollinations AI on the frontend
    },
    history_id: historyRecord._id,
  })
})

/**
 * GET /api/history
 */
const getHistory = asyncHandler(async (req, res) => {
  const { limit, skip } = req.query
  const { records, total } = await HistoryService.getAll({ limit, skip })
  res.status(200).json({
    success: true,
    count:   records.length,
    total,
    data:    records.map(formatHistory),
  })
})

/**
 * GET /api/history/:id
 */
const getHistoryById = asyncHandler(async (req, res) => {
  const record = await HistoryService.getById(req.params.id)
  res.status(200).json({ success: true, data: formatHistory(record) })
})

module.exports = { predictHybrid, getHistory, getHistoryById }