// models/PredictionHistory.js
// Stores every hybrid prediction that has been made.

const mongoose = require('mongoose')

const predictedTraitsSchema = new mongoose.Schema(
  {
    height:      { type: Number   },
    leaf_shape:  { type: String   },
    flower_color:{ type: String   },
    climate:     { type: String   },
    resistance:  { type: String   },
    growth_days: { type: Number   },
    yield_level: { type: String   },
  },
  { _id: false }
)

const predictionHistorySchema = new mongoose.Schema(
  {
    // Parent plant A
    plantA: {
      type: String,
      required: [true, 'plantA name is required'],
      trim: true,
      index: true,
    },

    // Parent plant B
    plantB: {
      type: String,
      required: [true, 'plantB name is required'],
      trim: true,
      index: true,
    },

    // Snapshots of parent data at time of prediction
    plantA_data: {
      type: mongoose.Schema.Types.Mixed,
      default: null,
    },
    plantB_data: {
      type: mongoose.Schema.Types.Mixed,
      default: null,
    },

    // Predicted hybrid name (may be supplied by ML or derived)
    predicted_hybrid: {
      type: String,
      trim: true,
      default: '',
    },

    // The 7 predicted traits
    predicted_traits: {
      type: predictedTraitsSchema,
      required: [true, 'predicted_traits is required'],
    },

    // Descriptive text for each predicted trait (generated by dataTransform)
    trait_descriptions: {
      type: mongoose.Schema.Types.Mixed,
      default: {},
    },

    hybrid_image_url: {
      type: String,
      default: '',
    },

    // Source of prediction
    prediction_source: {
      type: String,
      enum: ['ml_api'],
      default: 'ml_api',
    },

    // ISO date string for display
    prediction_date: {
      type: String,
      default: () => new Date().toISOString().split('T')[0], // "YYYY-MM-DD"
    },
  },
  {
    timestamps: true,  // adds createdAt + updatedAt
    toJSON:   { virtuals: true },
    toObject: { virtuals: true },
  }
)

// ── Compound index for duplicate detection ────────────────────────────────────
predictionHistorySchema.index({ plantA: 1, plantB: 1, createdAt: -1 })

// ── Virtual: formatted pair label ────────────────────────────────────────────
predictionHistorySchema.virtual('pairLabel').get(function () {
  return `${this.plantA} × ${this.plantB}`
})

module.exports = mongoose.model('PredictionHistory', predictionHistorySchema)